/**
 * Regenerate the self-hosted webfonts and `src/styles/base/fonts.css`.
 *
 * Run with `node scripts/fetch-fonts.mjs` after adding a family, or when a
 * Google Fonts version bumps. Deliberately not part of the build: the woff2
 * files are committed, so a network hiccup can never break a deploy.
 *
 * Only the `latin` and `latin-ext` subsets are kept — the app is Dutch, and the
 * cyrillic/greek/vietnamese subsets Google also serves would be dead weight.
 * All three families are variable, so one file per subset covers the whole
 * weight range and each face is declared with a weight *range* rather than one
 * @font-face per step.
 */

import { execSync } from 'node:child_process'
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const FONT_DIR = resolve(ROOT, 'src/assets/fonts')
const CSS_FILE = resolve(ROOT, 'src/styles/base/fonts.css')

/** Chrome, so the API answers with woff2 rather than a legacy format. */
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36'

const KEEP_SUBSETS = new Set(['latin', 'latin-ext'])

const FAMILIES = [
  { query: 'Outfit:wght@400;500;600;700', family: 'Outfit', slug: 'outfit', weight: '400 700' },
  { query: 'Manrope:wght@400;500;600;700', family: 'Manrope', slug: 'manrope', weight: '400 700' },
  {
    query: 'JetBrains+Mono:wght@400;500',
    family: 'JetBrains Mono',
    slug: 'jetbrains-mono',
    weight: '400 500',
  },
]

const HEADER = `/*
  Studio typefaces, self-hosted.

  Three faces, each with a job: Outfit for headings and the big numerals,
  Manrope for every other piece of UI text, JetBrains Mono for IDs, dates,
  measurements and shortcut keys — the things that have to line up in a column
  and read as data rather than as prose.

  Generated by scripts/fetch-fonts.mjs. Edit that, not this.
*/`

function fetchCss(query) {
  return execSync(
    `curl -sSf -A ${JSON.stringify(UA)} ` +
      `"https://fonts.googleapis.com/css2?family=${query}&display=swap"`,
    { encoding: 'utf8' },
  )
}

mkdirSync(FONT_DIR, { recursive: true })

const faces = []

for (const font of FAMILIES) {
  const css = fetchCss(font.query)
  // Google prefixes each face with a `/* subset */` comment; that comment is
  // the only place the subset name appears, so parse the pair together.
  const pattern = /\/\*\s*([a-z-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g
  const seen = new Set()

  for (const [, subset, body] of css.matchAll(pattern)) {
    if (!KEEP_SUBSETS.has(subset) || seen.has(subset)) continue
    seen.add(subset)

    const url = body.match(/url\((https:[^)]+)\)/)?.[1]
    const unicodeRange = body.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim()
    if (!url || !unicodeRange) throw new Error(`Unparsable face for ${font.family}/${subset}`)

    const filename = `${font.slug}-${subset}.woff2`
    execSync(`curl -sSf -o ${JSON.stringify(`${FONT_DIR}/${filename}`)} ${JSON.stringify(url)}`)

    faces.push(
      [
        `/* ${font.family} — ${subset} */`,
        `@font-face {`,
        `  font-family: "${font.family}";`,
        `  font-style: normal;`,
        `  font-weight: ${font.weight};`,
        `  font-display: swap;`,
        `  src: url("@assets/fonts/${filename}") format("woff2");`,
        `  unicode-range: ${unicodeRange};`,
        `}`,
      ].join('\n'),
    )
  }
}

writeFileSync(CSS_FILE, `${HEADER}\n\n${faces.join('\n\n')}\n`)
console.log(`wrote ${faces.length} faces to ${CSS_FILE}`)
